language: java

sudo: required

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

install:
  - export MAVEN_HOME=/usr/local/maven-3.5.0

script:
  - mvn clean install
  - mvn package -DskipTests
  - java -jar dspot/target/dspot-1.0.0-jar-with-dependencies.jar --example


after_success:
  - mvn clean test jacoco:report coveralls:report